#!/bin/bash
set -e

rm -f /var/run/mariadb/mariadb.pid

exec /usr/libexec/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib64/mysql/plugin --user=mysql \
                         --log-error=/var/log/mariadb/mariadb.log --pid-file=/var/run/mariadb/mariadb.pid \
                         --socket=/var/lib/mysql/mysql.sock
